version: "3.8"
services:
  shop:
    build: .
    volumes:
      - .:/django
    ports:
      - 9000:9000
    image: shop:django
    container_name: shop_container
    command: python manage.py runserver 0.0.0.0:9000
    depends_on:
      - db
      - celery
      - celery-beat

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: database

  redis:
    image: redis
    container_name: redis_container

  celery:
    restart: always
    build:
      context: .
    command: celery -A CampitShop worker -l info
    volumes:
      - .:/django
    container_name: celery_container
    depends_on:
      - redis

  celery-beat:
    build: .
    command: celery -A CampitShop beat -l info
    volumes:
      - .:/django
    depends_on:
      - redis

  zookeeper:
    image: zookeeper
    restart: always
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

