version: "3.8"
services:
  shop:
    build: .
    volumes:
      - .:/django
    ports:
      - 9000:9000
    image: shop:django
    container_name: shop_container
    command: python manage.py runserver 0.0.0.0:9000
    depends_on:
      - db

  db:
      image: postgres
      volumes:
        - ./data/db:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      container_name: database







