# Generated by Django 4.0.5 on 2022-07-02 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_rename_email_newsletter_newsletter_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
