# Generated by Django 4.0.5 on 2022-07-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_newsletter_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='newsletter_email',
            field=models.EmailField(max_length=255),
        ),
    ]
